### ISSUE TITLE
Can't fetch URLs

### ISSUE THREAD

**Issue by ranlandau** [jlubawy/go-boilerpipe#1]
Hi,

I'm currently using boilerpipe.
I'm trying to switch to this new package, GoLang based which looks maintained.

I've downloaded the code,
did go get for the relevant packaages, and did go build main.go

then ran 
main -http :8080

when navigating there and trying any url i get

Get https://dealbook.nytimes.com/2006/09/12/big-names-pull-cash-from-venture-capital-fund-over-political-contributions?_r=4: stopped after 10 redirects

Any idea?

Thanks.

**Comment by jlubawy** [comment]
Hi Ran,

I looked into it and that URL was being redirected to a login page, cookies needed to be enabled in the HTTP client for the redirect to work correctly. For more details see http://stackoverflow.com/questions/20986395/why-does-curl-not-work-but-wget-works.

I'm closing the issue as fixed in v0.0.7, let me know if you have any more issues.

Thanks,
Josh
