### ISSUE TITLE
Question: Why are nested `<a/>` Elements an issue?

### ISSUE THREAD

**Issue by chrisUsick** [jlubawy/go-boilerpipe#10]
I haven't dug into the code but when I try to parse websites with nested anchor elements I get the `input contains nested <a> elements` [source link](https://github.com/jlubawy/go-boilerpipe/blob/a010997fb997a9f62f0a1fc913d4dde8159c4730/content_handler.go#L455).

Why does this cause an issue, and is there any workarounds for this?

**Comment by jlubawy** [comment]
This is an artifact from porting from the original Java boilerpipe: https://github.com/kohlschutter/boilerpipe/blob/2c78035a830282e2435c466f3f14d6d4104d0a94/boilerpipe-common/src/main/java/com/kohlschutter/boilerpipe/sax/CommonTagActions.java#L96

I think I was just too lazy to handle is any other way except as an error since all the HTML I've parsed hasn't had any nested anchors and never ran into this situation.

I'll either add a 'warnings' method or remove this as an error, since it shouldn't affect the ability to parse a document.

If you already have a solution let me know in a pull-request.

**Comment by jlubawy** [comment]
Try v0.2.3: https://github.com/jlubawy/go-boilerpipe/commit/1c559801ddd5282c236089e54582bfee9ad6e5e9

I changed some parser errors into warnings, you can check for them if you want but they shouldn't affect the accuracy of the content extracted (from what I can tell).

I'm hoping to add some more robust testing for stuff like this in the future. Thanks for reporting it and let me know if you have more problems.
